export const MORE_INGREDIENT = 'MORE_INGREDIENT'
export const LESS_INGREDIENT = 'LESS_INGREDIENT'
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

export const STORE_ORDERS = 'STORE_ORDERS'
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'

export const PLACE_ORDER_FAILED = 'PLACE_ORDER_FAILED'
export const STORE_ORDER = 'STORE_ORDER'
export const MODAL_HIDE = 'MODAL_HIDE'
export const SHOW_LOADER = 'SHOW_LOADER'

export const AUTH_USER = 'AUTH_USER'  // for saga
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const CHECK_AUTH_TIMEOUT = 'CHECK_AUTH_TIMEOUT'   //for saga
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT'  // for saga
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

//export const SET_REDIRECT_AUTH_PATH = 'SET_REDIRECT_AUTH_PATH' 

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'
export const AUTH_SUCCESS_ON_REFRESH = 'AUTH_SUCCESS_ON_REFRESH'
export const AUTH_CHECK_STATE_FOR_SAGA = 'AUTH_CHECK_STATE_FOR_SAGA'  // for saga